---
Gemfile:
  optional:
    ':test':
      - gem: 'rspec-json_expectations'
spec/spec_helper.rb:
  spec_overrides:
    - "require 'rspec/json_expectations'"
spec/spec_helper_acceptance.rb:
  unmanaged: false
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
